name             'chef-install-scripts'
maintainer       'Stephane LII'
maintainer_email 'stephane.lii@informatique.gov.pf'
license          'All rights reserved'
description      'Installs/Configures chef-install-scripts'
long_description 'Installs/Configures chef-install-scripts'
version          '0.1.0'
depends 'apt'
