name             'chef-install-scripts'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chef-install-scripts'
long_description 'Installs/Configures chef-install-scripts'
version          '0.1.0'
